language: python
python:
  - "3.6"
  - "3.7-dev"  # 3.7 development branch

before_script:
  - pip install -r pytest-cov

install:
  - pip install .
# command to run tests

script:
  - pytest --cov=FolderAnalyse -v
